name: Build and Deploy Vario

on:
push:
branches:
- QA

permissions:
contents: write

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: "20"

  - name: Install dependencies
    run: npm install

  - name: Build Angular project
    run: npx ng build --configuration production --base-href "/Vario/"

  - name: Copy index.html to 404.html
    run: cp dist/vario/browser/index.html dist/vario/browser/404.html

  - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@v4
    with:
      folder: dist/vario/browser
      branch: gh-pages
