name: Build and Deploy Vario

on:
push:
branches:
- QA

permissions:
contents: write

jobs:
build-and-deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'

  - name: Install Dependencies
    run: npm install

  - name: Build Project
    run: npx ng build --configuration production --base-href "/Vario/"

  - name: Fix Angular Routing (404 fallback)
    run: cp dist/vario/browser/index.html dist/vario/browser/404.html

  - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@v4
    with:
      folder: dist/vario/browser
      branch: gh-pages
```
